version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    default_reviewers:
      - "gavinsharp"
