name: Release & Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@goproperly'
      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
#      - name: Release
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        run: npm run release
#      - name: Publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        run: npm publish
